### ISSUE TITLE
Crear div

### ISSUE THREAD

**Issue by patitonav** [lsia/cim2-framework#1]
Se deberia pasar de un pop_up a una ventana permanente.

**Comment by alegmarra** [comment]
En [el commit inicial para el div](https://github.com/lsia/cim2-framework/commit/079df039400c9eed0c0db85e30a115baf0e7b0a1) se puede ver un primer approach para esto. 

El popup sigue quedando, pero se utilizaría para configuraciones del plugin y no para log del chat.

Obviamente, es una version super alfa lo commiteado, hay que definir los próximos issues sobre lo que está.

**Comment by npersia** [comment]
Hola, por qué estaba yo en esta lista?

Nahuel Persia
Sr. Software Architect | Functional Analyst
Buenos Aires - Argentina.
Follow me LinkedIn <http://ar.linkedin.com/in/npersia>

2015-08-30 21:54 GMT-03:00 Alejandro García Marra <notifications@github.com>
:
